project:
  type: default
  output-dir: ../docs

execute:
  freeze: auto
  warning: true
  message: true

title: "University Rankings Analysis"
author: "Maksym Honchar"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-title: "Content"
    number-sections: true
    code-fold: true
    code-tools: true
    code-summary: "Show code"
    highlight-style: github
    fig-align: "center"
    fig-width: 9
    fig-height: 6
    lang: en
  pdf:
    include-in-header:
      text: |
        \usepackage{float}
        \raggedbottom
    toc: true
    toc-depth: 2
    toc-title: "Content"
    number-sections: true
    fig-align: "center"
    fig-width: 8
    fig-height: 5
    lang: en

bibliography: references.bib
csl: iso690-numeric-en.csl