project:
  type: default
  output-dir: ../docs
  resources:
    - figures/

execute:
  freeze: auto
  warning: true
  message: true

crossref:
  eq-prefix: ""

bibliography: references.bib
csl: apa.csl